### ISSUE TITLE
Licensing: opensource or not?

### ISSUE THREAD

**Issue by lrq3000** [jeeliz/jeelizPupillometry#10]
Hello,

It's an amazing software you made, thank you very much for sharing your work freely.

However, it seems to be described as a freeware, and only a minified version of the sourcecode is available, not the original sourcecode. The current license is set to Apache License 2.0, which is an opensource license and, I think (but IANAL), requires to share the source code.

You are of course entitled to your work, but could you please clarify whether this software is open source or not? If not, could you please change the license to something to adequately reflect the terms of use of your software?

Thank you very much!

**Comment by lrq3000** [comment]
Ah, it seems I'm really not a lawyer. The terms are correct, the Apache License 2.0 doesn't impose any condition on sharing the source code. My bad!

**Comment by xavierjs** [comment]
Hi,

This issue is related to this one: https://github.com/jeeliz/jeelizGlassesVTOWidget/issues/2
(It is another Jeeliz library but the question of minified sources is the same).

Best,
Xavier
