### ISSUE TITLE
Focus, optimization, slider settings and calibrating two eyes

### ISSUE THREAD

**Issue by Phonetiker** [jeeliz/jeelizPupillometry#3]
Hi Xavier,
Thanks for your responses so far. We have a few more questions:
1. Camera focus and placement: we're able to get good focus on the face when the eyes are relatively close to the camera (60cm) but the iris and pupil images showed blurring. At a distance of ~90-100cm, the focus seems a lot better. Is this consistent with your piloting of the setup?
2. In the ReadMe there's mentioned of "Optimization/Canvas and video resolutions" but the link doesn't seem to lead anywhere. I wondered whether that info might be available somewhere.
3. We're trying out the setup with a variety of people with different eye colors/eye make-up, and wondered whether you could provide any more information on how each of the four slider setting affects image segmentation/identification of the relevant eye elements/pupil diameter.
4. Very often, we're able to get good calibration, and good data from one eye but not from both simultaneously. Initially it seemed always to be the eye closest to the red light that was well calibrated, so we bought an extra lamp. However, even with two lamps, we continue to be able to calibrate just one eye well. Mostly the problem begins with iris segmentation--the window is shifted towards the outer edge of the participant's eye. Is there anything we might be overlooking that could be causing this?
Thanks!

**Comment by xavierjs** [comment]
Hi,

1. Yes, I had the same problem. If we are too close to the camera we need to adjust the lens to have a wider field of view, but then the lens is not able to focus accurately. But at the beginning the idea was to be able to put some distance between the user and the camera so it was not a problem for me... Maybe it you could try other lenses,

2. There was an error in the readme.md, it was a copy/paste from Jeeliz FaceFilter, I apologize,

3. Sure, I will add this information in the readme.md today,

4. This problem may not come from the lighting, but from the distance to the camera.
If you are too close to the camera, there will be a stronger fisheye effect and then the eyes will be further.
Then the eyes will be cropped with too distant frames. Does the problem still occur if the user is further to the camera ?

**Comment by xavierjs** [comment]
3. https://github.com/jeeliz/jeelizPupillometry#sliders-usage
