### ISSUE TITLE
speed-pupil

### ISSUE THREAD

**Issue by ciaoamigoschat** [jeeliz/jeelizPupillometry#5]
Is there a way to capture the speed with which the pupil moves?

**Comment by xavierjs** [comment]
This is not currently implemented but you can add this feature.
You have to compute the derivative of the pupil radius (and add some filtering)

**Comment by ciaoamigo** [comment]
Can you give me a hand / inspiration from where to start?

thanks

**Comment by xavierjs** [comment]
Yeah. By the readme.md
