### ISSUE TITLE
high speed video frame rate?

### ISSUE THREAD

**Issue by spincraft** [jeeliz/jeelizPupillometry#7]
I ordered a high speed camera to test with your pupil code.
This camera has a frame rate up to 120 fps.
I also want to run your ExperimentRecorder.js
Please let me know what parameters to change to match the camera frame rate.
THX

**Comment by xavierjs** [comment]
Hi @spincraft 

Do you manage to get the 120 FPS video in the web browser using getUserMedia API?
I noticed that the highest level camera parameters are often not accessible in the web browser.

Currently the rendering loop is based on the refresh rate of the display since window.requestAnimationFrame is used to launch each iteration. What is the refresh rate of your display device ? You should try with a 144Hz monitor to not have a bottleneck on this side.

Also you need quite powerful hardware (especially the GPU) to be sure it won't be the bottleneck.

**Comment by spincraft** [comment]
Thanks for your reply.
You mention several good points.
RE: getUserMedia API
My guess is that the response of this method is hardware dependant but I haven't tested it.

RE: display refresh rate
Yes, most monitors are 50/60 Hz refresh. That means the reporting ExperimentRecorder.js needs to keep up with the frame rate. The display will not keep up with the frame rate. The results will be provided after the experiment has concluded by the Recorder. It's code needs to modified to handle this high speed.

RE: 144 Hz monitor
The observer will not perceive the experiment since it happens too fast. I hope the ExperimentRecorder.js can handle this high speed.

RE: CPU vs. GPU
Yes, the GPU is capable of supporting the experiment.

**Comment by spincraft** [comment]
closed by mistake, please reopen.
sorry

**Comment by xavierjs** [comment]
Hi,

Plz first test if getUserMedia is able to handle your camera at 120FPS, and if yes, with which mediaConstraints. Which camera is it exactly?

**Comment by spincraft** [comment]
I ordered a custom PCB & components. It's a DIY camera project.
I'm waiting on the parts to arrive here.
How would I test getUserMedia without the camera?

**Comment by xavierjs** [comment]
I am not in a hurry

**Comment by spincraft** [comment]
Sorry, I didn't understand your reply.

**Comment by spincraft** [comment]
ref: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia
frame rate specifier
1  var constraints = { video: { frameRate: { ideal: 10, max: 15 } } };

**Comment by xavierjs** [comment]
I want you to test it with the real device.
I am not in a hurry, I can wait that you received your stuffs.

**Comment by xavierjs** [comment]
And also, if you want me to help you here, please provide more information about your project. If what you are doing is strictly confidential, okay, I can also provide private support & development service but I charge for that.

**Comment by spincraft** [comment]
Sorry, no insults were implied or intended.
