### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by spincraft** [jeeliz/jeelizPupillometry#8]
I tested both demos as posted up here. 
The luminous intensity of the screen and alternately images inspiring peace or fear do not show the results. I think I followed the procedures as listed. 
The face and pupil locations are found in Demo mode.
Start Experiment tab begins the test.
Stop Experiment gives the error msg;
"There are no results yet. Please run and complete an experiment before".
Thanks in advance for your comments.

**Comment by xavierjs** [comment]
I have fixed the bug, sorry for the long delay. I hope it will work now

**Comment by spincraft** [comment]
THX!
i will try it, again.
best regards

**Comment by xavierjs** [comment]
I hope your issue has been fixed. Feel free to re-open this issue if it does not.
